-- MySQL Schema for Jeisys Medical
-- Note: UUIDs should be generated by the application (e.g. using 'uuid' library) and stored as CHAR(36)

-- 1. Users Table
CREATE TABLE users (
  id CHAR(36) NOT NULL PRIMARY KEY,
  user_id VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  name VARCHAR(100) NOT NULL,
  hospital_name VARCHAR(100),
  hospital_email VARCHAR(255),
  tax_email VARCHAR(255),
  phone VARCHAR(20),
  mobile VARCHAR(20),
  business_number VARCHAR(50),
  zip_code VARCHAR(10),
  address TEXT,
  address_detail TEXT,
  region VARCHAR(100),
  business_certificate_url TEXT,
  email_notification BOOLEAN DEFAULT FALSE,
  holiday_week VARCHAR(50),
  holiday_day VARCHAR(50),
  is_public_holiday BOOLEAN DEFAULT FALSE,
  role ENUM('admin', 'user') DEFAULT 'user',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. Equipments Table
CREATE TABLE equipments (
  id CHAR(36) NOT NULL PRIMARY KEY,
  model_name VARCHAR(100) NOT NULL,
  code VARCHAR(50) UNIQUE,
  category VARCHAR(50),
  image_url TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3. User Equipments
CREATE TABLE user_equipments (
  id CHAR(36) NOT NULL PRIMARY KEY,
  user_id CHAR(36) NOT NULL,
  equipment_id CHAR(36) NOT NULL,
  serial_number VARCHAR(100),
  install_date DATE,
  warranty_end_date DATE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (equipment_id) REFERENCES equipments(id) ON DELETE CASCADE
);

-- 4. Products
CREATE TABLE products (
  id CHAR(36) NOT NULL PRIMARY KEY,
  sku VARCHAR(100) UNIQUE NOT NULL,
  name VARCHAR(255) NOT NULL,
  category VARCHAR(50),
  subcategory VARCHAR(50),
  description TEXT,
  price INT DEFAULT 0 NOT NULL,
  stock INT DEFAULT 0 NOT NULL,
  image_url TEXT,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 5. Product Images
CREATE TABLE product_images (
  id CHAR(36) NOT NULL PRIMARY KEY,
  product_id CHAR(36) NOT NULL,
  image_url TEXT NOT NULL,
  display_order INT DEFAULT 0,
  FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);

-- 6. Product Pricing Tiers
CREATE TABLE product_pricing_tiers (
  id CHAR(36) NOT NULL PRIMARY KEY,
  product_id CHAR(36) NOT NULL,
  min_quantity INT NOT NULL,
  unit_price INT NOT NULL,
  FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);

-- 7. Product Compatibility
CREATE TABLE product_compatibility (
  id CHAR(36) NOT NULL PRIMARY KEY,
  product_id CHAR(36) NOT NULL,
  equipment_id CHAR(36) NOT NULL,
  FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
  FOREIGN KEY (equipment_id) REFERENCES equipments(id) ON DELETE CASCADE
);

-- 8. Cart Items
CREATE TABLE cart_items (
  id CHAR(36) NOT NULL PRIMARY KEY,
  user_id CHAR(36) NOT NULL,
  product_id CHAR(36) NOT NULL,
  quantity INT DEFAULT 1 NOT NULL,
  is_subscription BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);

-- 9. Orders
CREATE TABLE orders (
  id CHAR(36) NOT NULL PRIMARY KEY,
  user_id CHAR(36),
  order_number VARCHAR(100) UNIQUE NOT NULL,
  status ENUM('pending', 'paid', 'processing', 'shipped', 'delivered', 'cancelled') DEFAULT 'pending',
  total_amount INT NOT NULL,
  payment_method VARCHAR(50),
  delivery_address TEXT,
  tracking_number VARCHAR(100),
  ordered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

-- 10. Order Items
CREATE TABLE order_items (
  id CHAR(36) NOT NULL PRIMARY KEY,
  order_id CHAR(36) NOT NULL,
  product_id CHAR(36),
  quantity INT NOT NULL,
  unit_price INT NOT NULL,
  total_price INT NOT NULL,
  FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
  FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL
);

-- 11. Posts
CREATE TABLE posts (
  id CHAR(36) NOT NULL PRIMARY KEY,
  type ENUM('notice', 'faq', 'news', 'media') NOT NULL,
  title VARCHAR(255) NOT NULL,
  content TEXT,
  view_count INT DEFAULT 0,
  is_visible BOOLEAN DEFAULT TRUE,
  image_url TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 12. Inquiries
CREATE TABLE inquiries (
  id CHAR(36) NOT NULL PRIMARY KEY,
  user_id CHAR(36),
  type VARCHAR(50) NOT NULL,
  title VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  is_secret BOOLEAN DEFAULT TRUE,
  status ENUM('waiting', 'answered') DEFAULT 'waiting',
  answer_content TEXT,
  answered_at TIMESTAMP NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);
